### ISSUE TITLE
Argument of type '{ urn: string; }' is not assignable to parameter of type 'CustomResourceOptions'.

### ISSUE THREAD

**Issue by retgits** [pulumi/pulumi-provider-boilerplate#13]
I want to try my hand at building a custom provider for Pulumi. After cloning the repo and running the commands in the README file, the provided example doesn't build correctly.

## Steps to reproduce

Stacktrace available at https://app.pulumi.com/retgits/simple/test/previews/fd8abb22-e851-40c3-b468-266802021d36

1. `git clone https://github.com/pulumi/pulumi-provider-boilerplate`
2. Followed the steps of `Build and Test` from the README.md file 
3. The first error I get was `Cannot find module '@pulumi/pulumi'.` which I solved with @jonne's suggestion in https://github.com/pulumi/pulumi-provider-boilerplate/issues/4
4. Running `pulumi up` results in the below stack trace

```bash
  pulumi:pulumi:Stack (simple-test):
    error: Running program '/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    ../../sdk/nodejs/index.ts(19,59): error TS2345: Argument of type '{ urn: string; }' is not assignable to parameter of type 'CustomResourceOptions'.
      Object literal may only specify known properties, and 'urn' does not exist in type 'CustomResourceOptions'.
    ../../sdk/nodejs/index.ts(25,16): error TS2339: Property 'registerResourceModule' does not exist on type 'typeof import("/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/index")'.
    ../../sdk/nodejs/index.ts(29,16): error TS2339: Property 'registerResourcePackage' does not exist on type 'typeof import("/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/index")'.
    ../../sdk/nodejs/index.ts(35,53): error TS2345: Argument of type '{ urn: string; }' is not assignable to parameter of type 'ResourceOptions'.
      Object literal may only specify known properties, and 'urn' does not exist in type 'ResourceOptions'.
    
        at createTSError (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:94:18)
```

When I look at the generated `index.ts` in the SDK folder, I see that error appear on line 19 & 35 (` return new Random(name, <any>undefined, { urn })`) and line 25 (`pulumi.runtime.registerResourceModule("xyz", "index", _module)`) shows `Property 'registerResourceModule' does not exist on type 'typeof import("/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/index")'.ts(2339)`

I'd love to help debug this, but I just don't know where to start.

**Comment by mikhailshilkov** [comment]
@retgits We've merged a PR with refactoring of this boilerplate repo today. Could you give this version a try?

**Comment by retgits** [comment]
@mikhailshilkov I've updated my fork (https://github.com/retgits/pulumi-provider-boilerplate) and updated the Makefile to exclude dotnet for now (I don't have the SDK on my machine).

Running the command `make build install` initially failed with

```bash
# Delete only files and folders that are generated.
rm -r sdk/python/pulumi_kubernetes/*/ sdk/python/pulumi_kubernetes/__init__.py
rm: sdk/python/pulumi_kubernetes/*/: No such file or directory
rm: sdk/python/pulumi_kubernetes/__init__.py: No such file or directory
make: *** [python_sdk] Error 1
```

So after commenting out that line, I was able to build everything successfully but I still got an error running the sample:

```bash
Diagnostics:
  pulumi:pulumi:Stack (simple-test):
    error: Running program '/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple' failed with an unhandled exception:
    Error: failed to register new resource my-random [xyz:index:Random]: 2 UNKNOWN: No Major.Minor.Patch elements found
        at Object.registerResource (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/resource.js:219:27)
        at new Resource (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/node_modules/@pulumi/pulumi/resource.js:217:24)
        at new CustomResource (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/node_modules/@pulumi/pulumi/resource.js:309:9)
        at new Random (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/sdk/nodejs/random.ts:32:9)
        at Object.<anonymous> (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/index.ts:4:16)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Module.m._compile (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/retgits/repos/retgits/pulumi-provider-boilerplate/examples/simple/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:981:32)
``` 

To validate, I also made a clean clone of this repository and it got me to the same result.

**Comment by mikhailshilkov** [comment]
Sorry for the trouble, let's try to debug this together.

It sounds like our `python_sdk` make target is broken (`kubernetes` slipped in instead of xyz) but you are using TypeScript so commenting it out is "fine".

Based on the error you get it looks like the node SDK didn't get the version populated. Could you check which version is in yor `sdk/nodejs/bin/package.json`? What if you run `VERSION=0.0.1 make build` (with an explicit version instead of relying on `pulumictl`)?

**Comment by mikhailshilkov** [comment]
Fixed by https://github.com/pulumi/pulumi-provider-boilerplate/pull/14
